import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import brikTokens from "./scripts/lib/eslint-brik-tokens.mjs";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run gen:types` — refresh via Supabase CLI.
    "src/types/supabase.ts",
    // Vendored BDS widgets synced by `scripts/sync-devbar-widgets.sh`.
    "public/**",
  ]),
  {
    // Typed token wrappers legitimately contain `var(--*)` strings — exempt.
    ignores: ["src/lib/tokens.ts", "src/lib/styles.ts"],
    plugins: { "brik-tokens": brikTokens },
    rules: { "brik-tokens/no-invented-tokens": "error" },
  },
]);

export default eslintConfig;
