#!/usr/bin/env node
// Regenerate Supabase TypeScript types from the staging project schema.
//
// Writes the `public` schema to `src/types/supabase.ts`. Run this after any
// migration that changes a table touched by brikdesigns code (services,
// service_lines, offerings, leads, blog_posts, etc.). The generated file is
// committed so consumers don't need DB access at build time.
//
// Introspects the database directly (`--db-url`). The old `--project-id` path
// delegated introspection to Supabase's hosted generator, which introspects
// with the project's legacy `service_role` key — disabled 2026-08-06, so it now
// fails with LegacyGenTypesUnexpectedStatusError on every CLI version, as does
// the Management API's own GET /v1/projects/{ref}/types/typescript. Server-side
// failure; no client-side key swap fixes it, and re-enabling legacy keys is not
// the fix. See brik-llm#3102.
//
// `--db-url` needs a container runtime (the CLI runs supabase/postgres-meta):
//   colima start          # on brik-mini; persist: brew services start colima
//
// Usage:
//   export SUPABASE_STAGING_DB_URL="$(op read \
//     'op://Development/d5vdzztvxceprflhsrqdl3xf3m/dbUrl')"   # supabase-db-portal-staging-url
//   npm run gen:types
//
// The staging project (lmhzpzobdkstzpvsqest) is shared with brik-client-portal
// — schema is owned there. brikdesigns regenerates its local view of it.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const PROJECT_ID = 'lmhzpzobdkstzpvsqest';
const OUT = path.resolve('src/types/supabase.ts');
const DB_URL = process.env.SUPABASE_STAGING_DB_URL;

if (!DB_URL) {
  console.error(
    'SUPABASE_STAGING_DB_URL is not set.\n' +
    "Run: export SUPABASE_STAGING_DB_URL=\"$(op read 'op://Development/d5vdzztvxceprflhsrqdl3xf3m/dbUrl')\"\n" +
    '     (purpose supabase-db-portal-staging-url — `brik-secrets show` it)'
  );
  process.exit(2);
}

// Fail on the prerequisite rather than on the CLI's container error, which
// buries the cause under a Docker Desktop install link.
try {
  execFileSync('docker', ['info', '--format', '{{.ServerVersion}}'], { stdio: 'ignore' });
} catch {
  console.error(
    'No reachable container runtime — `supabase gen types --db-url` needs one\n' +
    'to run supabase/postgres-meta (brik-llm#3102).\n' +
    'On brik-mini: colima start   (persist with: brew services start colima)'
  );
  process.exit(3);
}

console.log(`Generating types from project ${PROJECT_ID} → ${path.relative(process.cwd(), OUT)}`);

const header = [
  '// Auto-generated by `npm run gen:types` from Supabase project ' + PROJECT_ID + '.',
  '// DO NOT EDIT. To refresh:',
  '//   colima start && export SUPABASE_STAGING_DB_URL=… && npm run gen:types',
  '',
  '',
].join('\n');

let body;
try {
  body = execFileSync(
    'supabase',
    ['gen', 'types', 'typescript', '--db-url', DB_URL, '--schema', 'public'],
    { encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'], maxBuffer: 32 * 1024 * 1024 }
  );
} catch {
  console.error('supabase gen types failed — see the CLI output above.');
  process.exit(1);
}

// A truncated generation that still exits 0 would silently commit a schema
// smaller than reality — the same silent-freeze failure mode as #3102.
if (!body.includes('Tables: {')) {
  console.error('Generated output has no `Tables: {` block — refusing to write a partial schema.');
  process.exit(1);
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, header + body);
console.log(`Wrote ${body.split('\n').length} lines to ${path.relative(process.cwd(), OUT)}`);
