#!/usr/bin/env node
// Regenerate Supabase TypeScript types from the staging project schema.
//
// Writes the `public` schema to `src/types/supabase.ts`. Run this after any
// migration that changes a table touched by brikdesigns code (services,
// service_lines, offerings, leads, blog_posts, etc.). The generated file is
// committed so consumers don't need DB access at build time.
//
// Usage:
//   source ~/.secrets/supabase.env  # exports SUPABASE_ACCESS_TOKEN
//   npm run gen:types
//
// The staging project (lmhzpzobdkstzpvsqest) is shared with brik-client-portal
// — schema is owned there. brikdesigns regenerates its local view of it.

import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const PROJECT_ID = 'lmhzpzobdkstzpvsqest';
const OUT = path.resolve('src/types/supabase.ts');

if (!process.env.SUPABASE_ACCESS_TOKEN) {
  console.error(
    'SUPABASE_ACCESS_TOKEN is not set.\n' +
    'Run: source ~/.secrets/supabase.env  (then re-run npm run gen:types)'
  );
  process.exit(2);
}

console.log(`Generating types from project ${PROJECT_ID} → ${path.relative(process.cwd(), OUT)}`);

const header = [
  '// Auto-generated by `npm run gen:types` from Supabase project ' + PROJECT_ID + '.',
  '// DO NOT EDIT. To refresh:',
  '//   source ~/.secrets/supabase.env && npm run gen:types',
  '',
  '',
].join('\n');

let body;
try {
  body = execSync(
    `supabase gen types typescript --project-id ${PROJECT_ID} --schema public`,
    { encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'], maxBuffer: 32 * 1024 * 1024 }
  );
} catch (err) {
  console.error('supabase gen types failed. Check your access token + network.');
  process.exit(1);
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, header + body);
console.log(`Wrote ${body.split('\n').length} lines to ${path.relative(process.cwd(), OUT)}`);
