#!/usr/bin/env node
// Token-lint gate for brikdesigns.com.
//
// Three checks, all fatal:
//   1. Invented tokens — fails CI when src/**/*.{ts,tsx,css} reference a CSS
//      custom property that is neither (a) declared in BDS `dist/tokens.css`,
//      nor (b) declared project-locally in `src/app/globals.css`, nor (c)
//      listed in `scripts/tokens-allowlist.txt`.
//
//   2. Service-token family — fails CI when a CSS rule uses
//      `--background-service-*` on a section/hero/callout/etc. selector, or
//      `--surface-service-*` on a tag/badge/pill/button selector. See
//      .claude/references/service-token-decision-tree.md for the rule.
//
//   3. Token-family ↔ property pairing — fails CI when a token's family
//      doesn't match the CSS property it's applied to (e.g. --text-* on
//      background-color). Mirrors brik-bds Rule 5 (brik-bds#578/#778).
//      Escape hatch: add `/* bds-lint-ignore token-family — <reason> */`
//      on the same line.
//
// Why: brikdesigns#93 (invented check) + brikdesigns#116 (service-family)
// + brikdesigns#284 (property-family) — all three keep wrong-token usage
// from creeping in silently.
//
// Usage:
//   npm run lint:tokens                  # all checks
//   npm run lint:tokens -- --write-allowlist   # regenerate allowlist from
//                                              # current invented-token
//                                              # violations (transitional)

import fs from 'node:fs';
import path from 'node:path';
import { glob } from 'glob';
import {
  loadTokenSets,
  findVarRefs,
  isViolation,
  findFamilyViolations,
  checkTokenFamilyPairing,
  PATHS,
} from './lib/canonical-tokens.mjs';

const args = new Set(process.argv.slice(2));
const WRITE_ALLOWLIST = args.has('--write-allowlist');

const sets = loadTokenSets();
const checkSets = WRITE_ALLOWLIST ? { ...sets, allowlist: new Set() } : sets;

const files = await glob('src/**/*.{ts,tsx,css}', {
  ignore: ['**/*.d.ts', '**/node_modules/**'],
});

const inventedViolations = [];
const familyViolations = [];
const pairingViolations = [];

for (const file of files) {
  const text = fs.readFileSync(file, 'utf8');
  const lines = text.split('\n');
  lines.forEach((line, idx) => {
    for (const { name } of findVarRefs(line)) {
      if (isViolation(name, checkSets)) {
        inventedViolations.push({
          file,
          line: idx + 1,
          token: name,
          snippet: line.trim().slice(0, 120),
        });
      }
    }
    // Rule 3: token-family ↔ property pairing (CSS + TSX/TS)
    pairingViolations.push(...checkTokenFamilyPairing(line, idx + 1, file));
  });

  // Rule 2: service-token family (CSS only — full-text walker)
  if (file.endsWith('.css')) {
    familyViolations.push(...findFamilyViolations(file, text));
  }
}

if (WRITE_ALLOWLIST) {
  const tokens = [...new Set(inventedViolations.map((v) => v.token))].sort();
  const body = [
    '# scripts/tokens-allowlist.txt',
    "# Transitional allowlist for invented tokens that haven't been migrated yet.",
    '# Generated by `npm run lint:tokens -- --write-allowlist`.',
    '# Goal: drive this list to zero (Bucket A migration work).',
    '#',
    '# Format: one bare token name per line. `#` starts a comment.',
    '',
    ...tokens.map((t) => t.replace(/^--/, '')),
    '',
  ].join('\n');
  fs.writeFileSync(PATHS.allowlist, body);
  console.log(
    `Wrote ${tokens.length} tokens to ${path.relative(process.cwd(), PATHS.allowlist)}`
  );
  process.exit(0);
}

const totalViolations = inventedViolations.length + familyViolations.length + pairingViolations.length;

if (totalViolations === 0) {
  console.log(
    `OK — ${files.length} files scanned, no invented tokens, no family mismatches, no pairing violations.`
  );
  process.exit(0);
}

// ── Invented tokens ─────────────────────────────────────────────────────────
if (inventedViolations.length > 0) {
  console.error(
    `FAIL — ${inventedViolations.length} invented-token reference(s):\n`
  );
  const byToken = {};
  for (const v of inventedViolations) {
    (byToken[v.token] ??= []).push(v);
  }
  for (const token of Object.keys(byToken).sort()) {
    const refs = byToken[token];
    console.error(
      `  ${token}  (${refs.length} use${refs.length === 1 ? '' : 's'})`
    );
    for (const r of refs.slice(0, 3)) {
      console.error(`    ${r.file}:${r.line}  ${r.snippet}`);
    }
    if (refs.length > 3) console.error(`    + ${refs.length - 3} more`);
  }
  console.error('\nFix options:');
  console.error(
    '  1. Use a canonical token from node_modules/@brikdesigns/bds/dist/tokens.css'
  );
  console.error(
    '  2. Declare project-locally in src/app/globals.css (last-resort)'
  );
  console.error(
    '  3. Add to scripts/tokens-allowlist.txt with a TODO (transitional only)'
  );
}

// ── Service-token family mismatches ─────────────────────────────────────────
if (familyViolations.length > 0) {
  if (inventedViolations.length > 0) console.error('');
  console.error(
    `FAIL — ${familyViolations.length} service-token family mismatch(es):\n`
  );
  for (const v of familyViolations) {
    console.error(`  ${v.file}:${v.line}  ${v.snippet}`);
    console.error(
      `    Selector \`${v.selector}\` classified as ${v.classification} (expects --${v.expectedFamily}-service-*).`
    );
    console.error(`    Use ${v.suggestedToken} instead of ${v.token}.`);
    console.error('');
  }
  console.error(
    'Rule: --surface-service-* = sections/cards; --background-service-* = badges/tags/buttons.'
  );
  console.error(
    'See .claude/references/service-token-decision-tree.md for the full decision tree.'
  );
  console.error(
    'Escape hatch (rare): add `/* lint-tokens-ignore-family */` on the same line as the var().'
  );
}

// ── Token-family ↔ property pairing ─────────────────────────────────────────
if (pairingViolations.length > 0) {
  if (inventedViolations.length > 0 || familyViolations.length > 0) console.error('');
  console.error(
    `FAIL — ${pairingViolations.length} token-family pairing violation(s):\n`
  );
  for (const v of pairingViolations) {
    console.error(`  ${v.file}:${v.line}  ${v.snippet}`);
    console.error(
      `    "${v.prop}: var(${v.tokenName})" — ${v.family}-family token in ${v.label} slot.`
    );
    console.error(`    Fix: ${v.suggestion}.`);
    console.error('');
  }
  console.error('Rule: token family must match the CSS property slot.');
  console.error('  --background-*/--surface-*  →  background / background-color');
  console.error('  --text-*/--color-*          →  color');
  console.error('  --border-*/--background-*   →  border-color / border-*-color / outline-color');
  console.error(
    'Escape hatch: add `/* bds-lint-ignore token-family — <reason> */` on the same line.'
  );
}

process.exit(1);
