#!/usr/bin/env node
// Token-lint gate for brikdesigns.com.
//
// Fails CI when src/**/*.{ts,tsx,css} reference a CSS custom property that is
// neither (a) declared in BDS `dist/tokens.css`, nor (b) declared project-
// locally in `src/app/globals.css`, nor (c) listed in
// `scripts/tokens-allowlist.txt`.
//
// Why: brikdesigns#TBD enforcement-gates — keeps invented `--surface-*` /
// `--page-accent` shapes from creeping back in. CLAUDE.md non-negotiable.
//
// Usage:
//   npm run lint:tokens                  # check everything
//   npm run lint:tokens -- --write-allowlist   # regenerate allowlist from
//                                              # current violations
//                                              # (transitional baselines only)

import fs from 'node:fs';
import path from 'node:path';
import { glob } from 'glob';
import { loadTokenSets, findVarRefs, isViolation, PATHS } from './lib/canonical-tokens.mjs';

const args = new Set(process.argv.slice(2));
const WRITE_ALLOWLIST = args.has('--write-allowlist');

const sets = loadTokenSets();
const checkSets = WRITE_ALLOWLIST
  ? { ...sets, allowlist: new Set() }
  : sets;

const files = await glob('src/**/*.{ts,tsx,css}', {
  ignore: ['**/*.d.ts', '**/node_modules/**'],
});

const violations = [];

for (const file of files) {
  const text = fs.readFileSync(file, 'utf8');
  const lines = text.split('\n');
  lines.forEach((line, idx) => {
    for (const { name } of findVarRefs(line)) {
      if (isViolation(name, checkSets)) {
        violations.push({
          file,
          line: idx + 1,
          token: name,
          snippet: line.trim().slice(0, 120),
        });
      }
    }
  });
}

if (WRITE_ALLOWLIST) {
  const tokens = [...new Set(violations.map((v) => v.token))].sort();
  const body = [
    '# scripts/tokens-allowlist.txt',
    '# Transitional allowlist for invented tokens that haven\'t been migrated yet.',
    '# Generated by `npm run lint:tokens -- --write-allowlist`.',
    '# Goal: drive this list to zero (Bucket A migration work).',
    '#',
    '# Format: one bare token name per line. `#` starts a comment.',
    '',
    ...tokens.map((t) => t.replace(/^--/, '')),
    '',
  ].join('\n');
  fs.writeFileSync(PATHS.allowlist, body);
  console.log(`Wrote ${tokens.length} tokens to ${path.relative(process.cwd(), PATHS.allowlist)}`);
  process.exit(0);
}

if (violations.length === 0) {
  console.log(`OK — ${files.length} files scanned, no invented tokens.`);
  process.exit(0);
}

console.error(`FAIL — ${violations.length} invented-token reference(s):\n`);
const byToken = {};
for (const v of violations) {
  (byToken[v.token] ??= []).push(v);
}
const sortedTokens = Object.keys(byToken).sort();
for (const token of sortedTokens) {
  const refs = byToken[token];
  console.error(`  ${token}  (${refs.length} use${refs.length === 1 ? '' : 's'})`);
  for (const r of refs.slice(0, 3)) {
    console.error(`    ${r.file}:${r.line}  ${r.snippet}`);
  }
  if (refs.length > 3) console.error(`    + ${refs.length - 3} more`);
}
console.error('\nFix options:');
console.error('  1. Use a canonical token from node_modules/@brikdesigns/bds/dist/tokens.css');
console.error('  2. Declare project-locally in src/app/globals.css (last-resort)');
console.error('  3. Add to scripts/tokens-allowlist.txt with a TODO (transitional only)');
process.exit(1);
